[package]
name = "fontsan"
version = "0.3.2"
authors = ["The Servo Project Developers"]
description = "Sanitiser for untrusted font files"
build = "build.rs"
license = "BSD-3-Clause"

[dependencies]
libc = "0.2.13"
miniz-sys = "0.1.7"

[build-dependencies]
cmake = "0.1"
